{{ if ne .Values.environment "local" -}}
---
kind: IngressSecret
apiVersion: di.fake.com/v1
metadata:
  name: {{ include "solana-helm.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1" # NOTE: Ingress secret needs to be deployed before gateway otherwise failure
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  cert: {{ .Values.environment | printf "certs/solana-helm-%s.crt" | .Files.Get | b64enc }}
  path_to_key: secret/default/{{ .Values.environment }}/{{ include "solana-helm.name" . }}/tlscert
  {{- end }}
